version: "3.9"

services:
  redis:
    image: redis:alpine
    networks:
      - application-network
    profiles:
      - deploy
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    networks:
      - application-network
    profiles:
      - deploy
  rabbitmq:
    image: rabbitmq:alpine
    networks:
      - application-network
    profiles:
      - deploy
  data:
    build:
      context: .
      dockerfile: DataService/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - Logging__Console__FormatterName=""
    networks:
      - application-network
    profiles:
      - deploy
  api:
    build:
      context: .
      dockerfile: ApiService/Dockerfile
    depends_on:
      - rabbitmq
      - data
      - redis
    environment:
      - Logging__Console__FormatterName=""
    ports:
      - 7170:80
    networks:
      - application-network
    profiles:
      - deploy
  integration-tests:
    container_name: integration-tests
    depends_on:
      - api
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - ./ApiService:/ApiService
      - ./Testing:/Testing
    working_dir: /Testing
    command: dotnet test
    environment:
      - API_URL=http://api:80/
    networks:
      - application-network
    profiles:
      - test
   
networks:
  application-network:
    name: application-network
